In [158]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.offline as py
import plotly.graph_objs as go

py.offline.init_notebook_mode(connected=True)

In [2]:
locations = pd.read_csv("locations.csv")
pickup_times =pd.read_csv("pickup_times.csv")

In [6]:
locations.head()

   location_id  longitude   latitude
0            1  24.941583  60.170870
1            2  24.934201  60.169802
2            3  24.938493  60.166408
3            4  24.940467  60.167048
4            5  24.938793  60.167518

In [16]:
pickup_times.head()

   location_id    iso_8601_timestamp  pickup_time
0            2  2019-01-13T19:32:53Z           20
1           55  2019-01-13T18:12:20Z           37
2           73  2019-01-10T18:13:26Z           33
3           46  2019-01-13T19:34:42Z           33
4           59  2019-01-08T16:11:42Z           21

In [7]:
locations.shape

(85, 3)

In [17]:
pickup_times.sort_values(by="iso_8601_timestamp")

       location_id    iso_8601_timestamp  pickup_time
8256            42  2019-01-07T10:00:06Z           13
22139           47  2019-01-07T10:00:08Z           23
47246           23  2019-01-07T10:00:10Z           21
33993           76  2019-01-07T10:00:13Z           40
45062           68  2019-01-07T10:00:14Z           31
33418           76  2019-01-07T10:00:19Z           21
13404           34  2019-01-07T10:00:23Z           25
46199           76  2019-01-07T10:00:29Z           18
64671           20  2019-01-07T10:00:32Z           30
60466           43  2019-01-07T10:00:34Z           33
21509           10  2019-01-07T10:00:35Z           33
61307            4  2019-01-07T10:00:38Z           17
15865            1  2019-01-07T10:00:40Z           25
46731            2  2019-01-07T10:00:44Z           22
9684            49  2019-01-07T10:00:53Z           33
29319           67  2019-01-07T10:00:55Z           29
5080            10  2019-01-07T10:00:58Z           23
26547           28  2019-01-07T10:00:58Z           13
41375            6  2019-01-07T10:01:02Z           33
61041           72  2019-01-07T10:01:03Z           26
19230           67  2019-01-07T10:01:05Z            5
51470           45  2019-01-07T10:01:06Z           33
48788           12  2019-01-07T10:01:08Z           27
5597            29  2019-01-07T10:01:13Z           40
41403           62  2019-01-07T10:01:25Z           21
2930            56  2019-01-07T10:01:27Z           36
31949           22  2019-01-07T10:01:27Z           28
6287            28  2019-01-07T10:01:28Z           12
39888           38  2019-01-07T10:01:31Z           16
37747           14  2019-01-07T10:01:33Z           12
...            ...                   ...          ...
61045           12  2019-01-13T19:58:42Z           13
63360           15  2019-01-13T19:58:43Z           39
9546            11  2019-01-13T19:58:52Z           12
30804           10  2019-01-13T19:58:53Z           29
5997            15  2019-01-13T19:58:57Z           13
13327           20  2019-01-13T19:58:59Z           14
12033            9  2019-01-13T19:59:03Z           26
35971           35  2019-01-13T19:59:09Z           28
63399           77  2019-01-13T19:59:09Z           18
64559           33  2019-01-13T19:59:12Z           32
50244           43  2019-01-13T19:59:17Z           15
51419           18  2019-01-13T19:59:17Z           11
29800           80  2019-01-13T19:59:19Z           24
27160           31  2019-01-13T19:59:21Z           24
19258           14  2019-01-13T19:59:21Z           28
21692           28  2019-01-13T19:59:26Z           31
63089           11  2019-01-13T19:59:27Z           25
35632            3  2019-01-13T19:59:34Z           20
12721           19  2019-01-13T19:59:34Z           30
32102           59  2019-01-13T19:59:37Z           31
39747            2  2019-01-13T19:59:41Z           19
59164           73  2019-01-13T19:59:41Z           11
8787            72  2019-01-13T19:59:43Z           28
30513           56  2019-01-13T19:59:44Z           28
22327           69  2019-01-13T19:59:44Z           34
35629           18  2019-01-13T19:59:47Z           30
7202            18  2019-01-13T19:59:47Z           37
16952           47  2019-01-13T19:59:48Z           30
44057           57  2019-01-13T19:59:57Z           22
21204           55  2019-01-13T19:59:58Z           31

[65380 rows x 3 columns]

In [8]:
pickup_times.shape

(65380, 3)

In [31]:
# Create a trace
trace = go.Scatter(
    x = locations.longitude,
    y = locations.latitude,
    mode = 'markers',
    marker=dict(
        size=16,
        color = np.random.randn(500), #set color equal to a variable
        colorscale='Viridis',
        showscale=True
    )
)
data = [trace]

In [32]:
py.iplot(data, filename='basic-scatter')

In [ ]:
def get_data


def calculate_median_pickup_times(city, date, hour_interval, write_to):

In [132]:
#pickup_times['date']  = pickup_times[]
#pickup_times = pickup_times.set_index(['date'])
#selected = pickup_times[(pickup_times['iso_8601_timestamp'] > '2019-01-12T16:59:40Z') & (pickup_times['iso_8601_timestamp'] <= '2019-01-12T23:59:40Z')]
selected = pickup_times[(pickup_times['iso_8601_timestamp'] > '2019-01-13T19:00:00Z') & (pickup_times['iso_8601_timestamp'] <= '2019-01-13T20:00:00Z')]

In [133]:
no_time = selected#selected[['location_id','pickup_time']]

In [134]:
no_time.head()

    location_id    iso_8601_timestamp  pickup_time
0             2  2019-01-13T19:32:53Z           20
3            46  2019-01-13T19:34:42Z           33
7            51  2019-01-13T19:40:31Z           11
16           76  2019-01-13T19:23:29Z           27
43           83  2019-01-13T19:04:32Z            7

In [135]:
no_time.shape

(1532, 3)

In [147]:
no_time = selected.groupby('location_id')
location_medians = no_time['pickup_time'].median()

In [152]:
location_medians.shape

(85,)

In [161]:
data = np.array([1,2,3,4,5])
data.shape

(5,)

In [159]:
indexes = location_medians.index.values
indexes.shape

(85,)

In [166]:
location_medians_with_index = pd.DataFrame(data={'location_id': indexes, 'median': location_medians}, columns=['location_id', 'median'])

In [167]:
location_medians_with_index

             location_id  median
location_id
1                      1    19.5
2                      2    20.5
3                      3    22.0
4                      4    18.0
5                      5    18.0
6                      6    23.0
7                      7    17.5
8                      8    22.5
9                      9    26.0
10                    10    29.0
11                    11    16.0
12                    12    23.0
13                    13    17.5
14                    14    24.0
15                    15    24.0
16                    16    18.0
17                    17    24.0
18                    18    24.0
19                    19    20.0
20                    20    20.0
21                    21    23.0
22                    22    18.0
23                    23    16.0
24                    24    17.0
25                    25    23.0
26                    26    20.0
27                    27    25.0
28                    28    34.0
29                    29    14.0
30                    30    16.0
...                  ...     ...
56                    56    34.0
57                    57    27.0
58                    58    26.0
59                    59    19.0
60                    60    18.0
61                    61    20.0
62                    62    22.0
63                    63    18.0
64                    64    22.0
65                    65    20.0
66                    66    18.5
67                    67    17.0
68                    68    23.0
69                    69    22.5
70                    70    26.5
71                    71    25.0
72                    72    25.5
73                    73    22.0
74                    74    29.0
75                    75    22.0
76                    76    21.0
77                    77    25.5
78                    78    20.0
79                    79    29.0
80                    80    21.0
81                    81    23.0
82                    82    33.0
83                    83    21.0
84                    84    26.5
85                    85    19.0

[85 rows x 2 columns]

In [141]:
location_medians_reshaped = location_medians.values.reshape(1,85)

In [142]:
location_medians_reshaped

array([[19.5, 20.5, 22. , 18. , 18. , 23. , 17.5, 22.5, 26. , 29. , 16. ,
        23. , 17.5, 24. , 24. , 18. , 24. , 24. , 20. , 20. , 23. , 18. ,
        16. , 17. , 23. , 20. , 25. , 34. , 14. , 16. , 21.5, 11. , 21. ,
        21.5, 23. , 24. , 16. , 17. , 21. , 19. , 25. , 28.5, 22. , 30. ,
        21. , 24.5, 30. , 17. , 25. , 25. , 17.5, 18. , 22. , 40.5, 34.5,
        34. , 27. , 26. , 19. , 18. , 20. , 22. , 18. , 22. , 20. , 18.5,
        17. , 23. , 22.5, 26.5, 25. , 25.5, 22. , 29. , 22. , 21. , 25.5,
        20. , 29. , 21. , 23. , 33. , 21. , 26.5, 19. ]])

In [121]:
s = selected.loc[selected['location_id'] == 80]
s['pickup_time'].median()

24.0

In [168]:
joined = location_medians_with_index.merge(locations, left_on='location_id', right_on='location_id', how='outer')

In [169]:
joined

    location_id  median  longitude   latitude
0             1    19.5  24.941583  60.170870
1             2    20.5  24.934201  60.169802
2             3    22.0  24.938493  60.166408
3             4    18.0  24.940467  60.167048
4             5    18.0  24.938793  60.167518
5             6    23.0  24.939866  60.166856
6             7    17.5  24.931755  60.168500
7             8    22.5  24.932313  60.168671
8             9    26.0  24.932828  60.168884
9            10    29.0  24.933643  60.169076
10           11    16.0  24.932914  60.167369
11           12    23.0  24.944329  60.172193
12           13    17.5  24.942355  60.170912
13           14    24.0  24.938064  60.169290
14           15    24.0  24.938064  60.169226
15           16    18.0  24.938450  60.169183
16           17    24.0  24.937763  60.169162
17           18    24.0  24.930210  60.163547
18           19    20.0  24.935575  60.165340
19           20    20.0  24.947119  60.170037
20           21    23.0  24.929609  60.166685
21           22    18.0  24.935832  60.163974
22           23    16.0  24.939222  60.165041
23           24    17.0  24.942055  60.163419
24           25    23.0  24.945445  60.163782
25           26    20.0  24.938021  60.172193
26           27    25.0  24.939866  60.168500
27           28    34.0  24.942141  60.168820
28           29    14.0  24.945273  60.167860
29           30    16.0  24.945059  60.168970
..          ...     ...        ...        ...
55           56    34.0  24.880643  60.160152
56           57    27.0  24.935961  60.199206
57           58    26.0  24.938107  60.199312
58           59    19.0  24.938450  60.198203
59           60    18.0  24.947548  60.193511
60           61    20.0  24.945831  60.194151
61           62    22.0  24.951754  60.192913
62           63    18.0  24.946346  60.185361
63           64    22.0  24.944115  60.184763
64           65    20.0  24.946260  60.184251
65           66    18.5  24.955444  60.179322
66           67    17.0  24.958277  60.179194
67           68    23.0  24.958277  60.178490
68           69    22.5  24.955959  60.178660
69           70    26.5  24.955573  60.180581
70           71    25.0  24.954500  60.181200
71           72    25.5  24.952912  60.180624
72           73    22.0  24.953470  60.185916
73           74    29.0  24.966130  60.186428
74           75    22.0  24.959650  60.186044
75           76    21.0  24.954457  60.182630
76           77    25.5  24.960937  60.180688
77           78    20.0  24.952397  60.171574
78           79    29.0  24.937420  60.168308
79           80    21.0  24.931412  60.170357
80           81    23.0  24.930468  60.161796
81           82    33.0  24.919910  60.163718
82           83    21.0  24.927034  60.179855
83           84    26.5  24.951153  60.159703
84           85    19.0  24.922485  60.156714

[85 rows x 4 columns]

In [181]:
colors = joined["median"].astype(int)
colors

0     19
1     20
2     22
3     18
4     18
5     23
6     17
7     22
8     26
9     29
10    16
11    23
12    17
13    24
14    24
15    18
16    24
17    24
18    20
19    20
20    23
21    18
22    16
23    17
24    23
25    20
26    25
27    34
28    14
29    16
      ..
55    34
56    27
57    26
58    19
59    18
60    20
61    22
62    18
63    22
64    20
65    18
66    17
67    23
68    22
69    26
70    25
71    25
72    22
73    29
74    22
75    21
76    25
77    20
78    29
79    21
80    23
81    33
82    21
83    26
84    19
Name: median, Length: 85, dtype: int32

In [188]:
# Create a trace

data = [
    go.Scatter(
        x=joined.longitude,
        y=joined.latitude,
        marker=dict(
            size=10,
            cmax=50,
            cmin=0,
            color=colors,
            colorbar=dict(
                title='Colorbar'
            ),
            colorscale='Viridis'
        ),
        mode='markers',
        text=joined["median"]
    
    )
]

In [189]:
py.iplot(data, filename='basic-scatter')